import pino, {
  type DestinationStream,
  type LevelWithSilent,
  type Logger,
  type LoggerOptions,
} from "pino";

export const LOG_REDACTION_PATHS = [
  "authorization",
  "Authorization",
  "cookie",
  "password",
  "confirmation",
  "currentPassword",
  "newPassword",
  "passwordConfirmation",
  "token",
  "bearerToken",
  "accessToken",
  "refreshToken",
  "secret",
  "gateError",
  "cronGateError",
  "databaseUrl",
  "DATABASE_URL",
  "DB_PASSWORD",
  "CRON_BEARER_TOKEN",
  "BYPUSULA_SYNC_SECRET",
  "READINESS_BEARER_TOKEN",
  "RESEND_API_KEY",
  "EMAIL_FROM_ADDRESS",
  "dbPassword",
  "readinessBearerToken",
  "apiKey",
  "fromAddress",
  "recipientEmail",
  "email",
  "recipient",
  "to",
  "from",
  "replyTo",
  "cc",
  "bcc",
  "subject",
  "text",
  "html",
  "message",
  "content",
  "body",
  "payload",
  "mail",
  "emailMessage",
  "emailPayload",
  "taxId",
  "amount",
  "finance",
  "customer",
  "headers.authorization",
  "headers.Authorization",
  "headers.cookie",
  "req.headers.authorization",
  "req.headers.Authorization",
  "req.headers.cookie",
  "res.headers.set-cookie",
  "*.authorization",
  "*.Authorization",
  "*.cookie",
  "*.password",
  "*.confirmation",
  "*.currentPassword",
  "*.newPassword",
  "*.passwordConfirmation",
  "*.token",
  "*.bearerToken",
  "*.accessToken",
  "*.refreshToken",
  "*.secret",
  "*.gateError",
  "*.cronGateError",
  "*.databaseUrl",
  "*.DB_PASSWORD",
  "*.CRON_BEARER_TOKEN",
  "*.BYPUSULA_SYNC_SECRET",
  "*.READINESS_BEARER_TOKEN",
  "*.RESEND_API_KEY",
  "*.EMAIL_FROM_ADDRESS",
  "*.dbPassword",
  "*.readinessBearerToken",
  "*.apiKey",
  "*.fromAddress",
  "*.recipientEmail",
  "*.email",
  "*.recipient",
  "*.to",
  "*.from",
  "*.replyTo",
  "*.cc",
  "*.bcc",
  "*.subject",
  "*.text",
  "*.html",
  "*.message",
  "*.content",
  "*.body",
  "*.payload",
  "*.mail",
  "*.emailMessage",
  "*.emailPayload",
  "*.taxId",
  "*.amount",
  "*.*.authorization",
  "*.*.Authorization",
  "*.*.RESEND_API_KEY",
  "*.*.EMAIL_FROM_ADDRESS",
  "*.*.apiKey",
  "*.*.fromAddress",
  "*.*.recipientEmail",
  "*.*.email",
  "*.*.recipient",
  "*.*.to",
  "*.*.from",
  "*.*.replyTo",
  "*.*.cc",
  "*.*.bcc",
  "*.*.subject",
  "*.*.text",
  "*.*.html",
  "*.*.message",
  "*.*.content",
  "*.*.body",
  "*.*.payload",
  "*.*.mail",
  "*.*.emailMessage",
  "*.*.emailPayload",
] as const;

function loggerOptions(level: LevelWithSilent): LoggerOptions {
  return {
    name: "portal-pusula",
    level,
    base: {
      service: "portal-pusula",
    },
    timestamp: pino.stdTimeFunctions.isoTime,
    redact: {
      paths: [...LOG_REDACTION_PATHS],
      censor: "[REDACTED]",
    },
  };
}

export function createAppLogger(
  level: LevelWithSilent,
  destination?: DestinationStream,
): Logger {
  return destination
    ? pino(loggerOptions(level), destination)
    : pino(loggerOptions(level));
}
